define Idris = Character("İdris-i Bitlis-i" ,image = "Idris Side" ,color = "#B7950B")
define Sahmeran = Character("Şahmeran", color = "#239B56")
define Memed = Character("Memed", color = "#CA6F1E")
define Ahmed = Character("Ahmed", color = "#273746")
define King = Character("The King of Tarsus", color = "#7B241C")
define Vizier = Character("Vizier", color = "#CB4335")
define Messenger = Character("Messenger", color = "#EC7063")
define BathAttendant = Character("Bath Attendant", color = "#2874A6")
define Devil = Character("Devil", color = "#884EA0")